{% set name = "dwavebinarycsp" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dwavebinarycsp-{{ version }}.tar.gz
  sha256: 7af07cd269809db94dbb4bee9b9cee437e9199fb42be6f2fcf68971a6f01bdbe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=46.4.0
    - wheel
  run:
    - dimod >=0.10.9,<0.13.0
    - networkx >=2.0,<3.0
    - penaltymodel >=1.0.0,<2.0.0
    - python >=3.7

test:
  imports:
    - dwavebinarycsp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwavebinarycsp
  summary: Solves constraints satisfaction problems with binary quadratic model samplers
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
